import Head from 'next/head';
import * as S from '../styles/Home.component';
import useAOS from '../hooks/useAOS';
import Hero from '../components/Hero/Hero';
import Step from '../components/Steps/Step';

export default function Home() {
  // custom aos hook
  useAOS();
  return (
    <S.Container>
      <Head>
        <title>GoLoKa: PreLaunch</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://unpkg.com/aos@2.3.1/dist/aos.css'
          rel='stylesheet'
        ></link>
      </Head>

      <Hero />
      <Step />
    </S.Container>
  );
}
